---
title: "fertility"
author: "Granát Marcell"
date: '2020 12 16'
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, warning=F}
knitr::opts_chunk$set(echo = F, comment = "", warning = F, message = F, cache = F, dev = "png", error = T)
library(tidyverse)
library(ggthemes)
theme_set(ggthemes::theme_economist() + theme(
  legend.title = element_blank(),
  plot.title = element_text(margin = margin(t = 0, r = 0, b = 10, l = 0)),
  axis.title = element_text(margin = margin(t = 10, r = 10, b = 0, l = 0)),
  axis.ticks.length = unit(5, "points"),
  panel.grid.major = element_line(colour = "grey", 
                                  size = rel(1.75))
))
load('fertility.Rdata')
```

```{r}
(p1 <- LiveBirthAndFertility %>% mutate_at(-1, function(x) x/x[1]) %>% 
  set_names("Year","Összes született gyermek", "Ezer nőre jutó született gyermekek száma", "Teljes termékenységi arány") %>% pivot_longer(-1) %>% 
 ggplot(aes(x = Year, y = value)) + 
  geom_line(aes(color = name), size = 2) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),expand=c(0,0),limits=c(0.5, 1.5)) +
  scale_x_continuous(expand=c(0,0)) +
  labs(title = "1. ábra. Születési mutatók bázisindexe", subtitle = "1960=100%",
       caption="A bázisindex használatát a három mutató együttesen való ábrázolásának céljából tartottam indokoltnak.", x = "Év", y = "Százalék") +
  scale_color_economist() +
  theme(
    legend.text = element_text(size = 10)
  ))
```

```{r}
(p2 <- LiveBirthAndFertility %>% select(Year, TotalFertility) %>% 
  ggplot(aes(x = Year, y = TotalFertility)) + 
  geom_hline(aes(yintercept = 2.1, color = "Az egyszerű reprodukciót jelentő érték"), size = 2, linetype = 'dashed') + 
  geom_line(aes(color = "Teljes termékenységi arány"), size = 2) +
  scale_y_continuous(expand=c(0.1,0.1)) +
  scale_x_continuous(expand=c(0,0)) +
  labs(title = "2. ábra. Magyarország termékenységi rátájának alakulása", subtitle="1960-2018",
  caption="Az ábra alapján jól látható, hogy az érték a vizsgált időszakban jelentősen a 2,1-es egyszerű reprodukció határát jelentő érték alatt maradt,\nglobális minimumát (1,23) pedig 2011-ben érte el.", x = "Év", y = "Gyermek/anya"
       ) +
  scale_color_manual(values = c("#e3120b", "#244747")))
```

```{r}
(t1 <- tibble::tribble(
  ~"Szerző", ~"Szerző által mely országra fogalmazódott meg a hipotézis", ~"Forrás alapján elemzésem fókuszába helyezett indikátorok",
  "*Tárkányi*", "Magyarország","jövedelem és foglalkoztatás mutatói",
  "*Cumming* és *Dettling*", "Egyesült Királyság", "megtakarítások és eladósodás mutatói",
  "*Levitt* és *Dubner*", "Egyesült Államok", "bűnözési statisztikák, császármetszések aránya",
  "*Duflo* és *Banerjee*", "India", "nyugdíjkifizetések mértéke, szegénységi mutatók"
) %>% data.frame() %>% set_names(c("Szerző", "Szerző által mely országra fogalmazódott meg a hipotézis", "Forrás alapján elemzésem fókuszába helyezett indikátorok")) %>%
  knitr::kable(caption = "1. táblázat. Szakirodalom áttekintése alapján dolgozatom témájának releváns gazdasági- és társadalmi indikátorainak köre", align = c("l",rep("c",2))) %>%
  kableExtra::kable_styling(bootstrap_options = "striped",full_width = T, fixed_thead = T))
```

```{r}
(p3 <- LiveBirthAndFertility %>% mutate(HP = mFilter::hpfilter(TotalFertility, freq = 100)$trend) %>% 
 ggplot(aes(x = Year)) + 
  geom_line(aes(y=TotalFertility, color = "Magyarország teljes termékenységi arányszáma"),linetype="solid", size = 2) +
  geom_line(aes(y=HP,color = "HP-szűrővel leválaszott trend"),linetype = "longdash", size = 2) +
  scale_y_continuous(expand=c(0,0), limits = c(0,2.5)) +
  scale_x_continuous(expand=c(0,0)) +
  labs(title = "3. ábra. Magyarország termékenységi rátájának alakulása és annak trendje", subtitle="1960-2018, Trend leválasztása Hodrick-Prescott szűrő segítségével (\u03b1 =100)", y = "Gyermek/anya", x = "Év") +
  scale_color_manual(values = c("#e3120b", "#244747")))
```

```{r}
(p4 <- LiveBirthAndFertility %>% select(Year, TotalFertility) %>% 
  mutate(TotalFertility = c(NA, diff(TotalFertility))) %>% 
  na.omit() %>% 
  {ggplot(data = .) +
  geom_hline(yintercept = 0, size=1.3, color="#4a4a4a") +
  geom_line(data = ., mapping = aes(Year, TotalFertility),  size = 2, color="#e3120b") +
  scale_y_continuous(expand=c(0,0), limits = c(-0.5, 0.5)) +
  scale_x_continuous(expand=c(0,0)) +
  labs(title = "4. ábra. Magyarország termékenységi rátájának növekménytagjai", subtitle="1961-2018, Differenciázás segítségével az eredeti idősor determinisztikus, illetve sztochasztikus trendje is eltávolítható", y = "Gyermek/anya", x = "Év")})
```

```{r}
(p5 <- LiveBirthAndFertility %>% pull(TotalFertility) %>% diff() %>% 
  {data.frame(lag = 0:20, "acf" = (acf(., plot = FALSE, lag.max = 20) %>% .$acf %>% data.frame() %>% pull(1)), "pacf" = (c(1, acf(., plot = FALSE, lag.max = 20, type = 'partial') %>% .$acf %>% data.frame() %>% pull(1))))} %>%
   pivot_longer(-1) %>% 
   mutate(name = ifelse(name == 'acf', "Korrelogram (ACF)", "Parciális korrelogram (PACF)")) %>% 
  ggplot(aes(x=lag, y=value)) +
  geom_hline(yintercept = 0, color="grey38", size=1) +
  geom_line(size=1.2, color="#244747") +
  geom_point( 
    shape=21, fill="#336666", color="#244747",size=3,stroke=1.5) +
  facet_wrap(~ name, ncol = 1) +
  labs(title="5. ábra. Magyarország termékenységi rátájának növekménytagjainak korrelogramja", subtitle="Autokorreláció és parciális autokorreláció függvény értékei egyes késleltetések mellett", x = "Késleltetés száma", y = NULL
  ) +
  scale_y_continuous(expand = c(0,0), limits = c(-1,1)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_economist(dkpanel = T) + theme(
    legend.title = element_blank(),
    plot.title = element_text(margin = margin(t = 0, r = 0, b = 10, l = 0)),
    axis.title = element_text(margin = margin(t = 10, r = 10, b = 0, l = 0)),
    axis.ticks.length = unit(5, "points"),
    panel.grid.major = element_line(colour = "grey", size = rel(1.75)),
    panel.spacing = unit(2, "lines")
  ))
```

```{r eval=FALSE}
diff(LiveBirthAndFertility$TotalFertility) %>% 
  head(-10) %>% 
  forecast::auto.arima(ic = "aicc",trace = T, method ="ML")
```


```{r echo=FALSE}
(t2 <- tibble::tribble(
  ~Modell,     ~AIC,
  "ARMA (2, 2) konstans nélkül", -242.885,
  "ARMA (0, 0) konstans nélkül", -240.849,
  "ARMA (1, 0) konstans nélkül", -245.811,
  "ARMA (0, 1) konstans nélkül", -247.251,
  "ARMA (0, 0) konstanssal", -241.485,
  "ARMA (1, 1) konstans nélkül", -243.801,
  "ARMA (0, 2) konstans nélkül", -244.906,
  "ARMA (1, 2) konstans nélkül", -242.047,
  "ARMA (0, 1) konstanssal", -248.674,
  "ARMA (1, 1) konstanssal", -245.643,
  "ARMA (0, 2) konstanssal", -246.473,
  "ARMA (1, 0) konstanssal", -247.669,
  "ARMA (1, 2) konstanssal",  -244.05
) %>% data.frame() %>% knitr::kable( caption = "2. táblázat. A magyar termékenységi arányszám növekménytagjaira illesztett ARMA-modellekhez tartozó információs kritériumok", align = c("l",rep("c",2))) %>%
  kableExtra::kable_styling(bootstrap_options = "striped",full_width = T, fixed_thead = T))
```

```{r}
LiveBirthAndFertility %>% select(-1) %>% 
  apply(2, function(x) c(
  tseries::adf.test(x)$p.value,
  tseries::adf.test(diff(x))$p.value,
  tseries::adf.test(log(x))$p.value,
  tseries::adf.test(diff(log(x)))$p.value
  )) %>% data.frame() %>% gather() %>% 
  {data.frame(var = c(rep("Összes születés",4),trans = rep("Ezer főre eső születés",4),rep("TTA",4)), rep(c("x","diff(x)","log(x)","diff(log(x))"),3), p = pull(., 2))} %>% 
  mutate(p = scales::percent(p, decimal.mark = ',')) %>% 
  set_names("Születési mutató","Transzformáció","ADF-teszthez tartozó p-érték") %>%
  knitr::kable(caption = "3. táblázat. Megfontolásra kerülő modellek", align = c("l",rep("c",3))) %>%
  kableExtra::kable_styling(bootstrap_options = "striped",full_width = T, fixed_thead = T)
```

```{r}
list(
  df = LiveBirthAndFertility %>% select(-1), f = function(df, method, transformation) {
    if (transformation == 'diff(x)') {
      f1 <- function(x) head(diff(x), -10)
      f2 <- function(x, model) sum(abs(tail(x, 10) - forecast::forecast(model, 10)$mean)/tail(x, 10) * 100) / 1000
    } else if (transformation == 'logdiff(x)') {
      f1 <- function(x) head(diff(log(x)), -10)
      f2 <- function(x, model) sum(abs((tail(exp(cumsum(c(log(x[1]), model$fitted, forecast::forecast(model, 10)$mean))), 10) - tail(x, 10))) / tail(x, 10) * 100) / 1000
    }
    apply(df, 2, function(x) 
    f1(x) %>% forecast::auto.arima(ic = 'aic', trace = F, method = method) %>% {
      c(transformation,
      paste("ARMA (", paste(.$arma[1:2], collapse = ", "), ")", sep = ""),
      method,
      scales::percent(f2(x = x, model = .), decimal.mark = ',', accuracy = .01),
      scales::percent(forecast::checkresiduals(., plot = F)$p.value, decimal.mark = ',', accuracy = .01),
      scales::percent(tseries::jarque.bera.test(na.omit(.$residuals))$p.value, decimal.mark = ',', accuracy = .01))}) %>%
   t() %>% data.frame %>% rownames_to_column()
  }
) %>% {
  .[[2]](.[[1]], method = 'CSS', transformation = 'diff(x)')
  }
```


```{r}
LiveBirthAndFertility %>% select(-1) %>% 
  {
    apply(., 2, function(x) 
    head(x, -10) %>% forecast::auto.arima(ic = 'aic', trace = F) %>% {
      c(paste("ARMA (", paste(.$arma[1:2], collapse = ", "), ")", sep =""),
      scales::percent(sum(abs(tail(x, 10) - forecast::forecast(., 10)$mean)/tail(x, 10) * 100) / 1000, decimal.mark = ',', accuracy = .01),
      scales::percent(forecast::checkresiduals(., plot = F)$p.value, decimal.mark = ',', accuracy = .01),
      scales::percent(tseries::jarque.bera.test(na.omit(.$residuals))$p.value, decimal.mark = ',', accuracy = .01))}) %>%
   t() %>% data.frame %>% rownames_to_column()
    }
```


```{r}
MyArima = auto.arima(diff(log(x)),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[8] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[8] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[8] = checkresiduals(MyArima, plot = F)$p.value
x4[8] = jarque.bera.test(na.omit(MyArima$residuals))$p.value


```


```{r}
x1 = 1:12 #collector vectors
x2 = 1:12
x3 = 1:12
x4 = 1:12
x = ts(LiveBirthAndFertility$LiveBirthTotal)
MyArima = auto.arima(head(x,-10), ic = "aic", trace = F)
x1[1] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[1] = sum(abs(tail(x, 10) - forecast(MyArima, 10)$mean) /
              tail(x, 10) * 100) / 10
x3[1] = checkresiduals(MyArima, plot = F)$p.value
x4[1] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(head(x,-10),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[2] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[2] = sum(abs(tail(x, 10) - forecast(MyArima, 10)$mean) /
              tail(x, 10) * 100) / 10
x3[2] = checkresiduals(MyArima, plot = F)$p.value
x4[2] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(diff(log(head(x,-10))), ic = "aic", trace = F)
x1[3] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[3] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[3] = checkresiduals(MyArima, plot = F)$p.value
x4[3] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(diff(log(x)),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[4] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[4] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[4] = checkresiduals(MyArima, plot = F)$p.value
x4[4] = jarque.bera.test(na.omit(MyArima$residuals))$p.value


x = ts(LiveBirthAndFertility$LiveBirthTo1000)
MyArima = auto.arima(head(x,-10), ic = "aic", trace = F)
x1[5] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[5] = sum(abs(tail(x, 10) - forecast(MyArima, 10)$mean) /
              tail(x, 10) * 100) / 10
x3[5] = checkresiduals(MyArima, plot = F)$p.value
x4[5] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(head(x,-10),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[6] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[6] = sum(abs(tail(x, 10) - forecast(MyArima, 10)$mean) /
              tail(x, 10) * 100) / 10
x3[6] = checkresiduals(MyArima, plot = F)$p.value
x4[6] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(diff(log(head(x,-10))), ic = "aic", trace = F)
x1[7] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[7] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[7] = checkresiduals(MyArima, plot = F)$p.value
x4[7] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(diff(log(x)),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[8] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[8] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[8] = checkresiduals(MyArima, plot = F)$p.value
x4[8] = jarque.bera.test(na.omit(MyArima$residuals))$p.value



x = ts(LiveBirthAndFertility$TotalFertility)
MyArima = auto.arima(head(x,-10), ic = "aic", trace = F)
x1[9] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                "")
x2[9] = sum(abs(tail(x, 10) - forecast(MyArima, 10)$mean) /
              tail(x, 10) * 100) / 10
x3[9] = checkresiduals(MyArima, plot = F)$p.value
x4[9] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(head(x,-10),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[10] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                 "")
x2[10] = sum(abs(tail(x, 10) - forecast(MyArima, 10)$mean) /
               tail(x, 10) * 100) / 10
x3[10] = checkresiduals(MyArima, plot = F)$p.value
x4[10] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(diff(log(head(x,-10))), ic = "aic", trace = F)
x1[11] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                 "")
x2[11] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[11] = checkresiduals(MyArima, plot = F)$p.value


x4[11] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

MyArima = auto.arima(diff(log(x)),
                     ic = "aic",
                     trace = F,
                     method = "CSS")
x1[12] = paste("ARMA (", paste(MyArima$arma[1:2], collapse = ", "), ")", sep =
                 "")
x2[12] = sum(abs((tail(exp(
  cumsum(c(
    log(x[1]), MyArima$fitted, forecast(MyArima, 10)$mean
  ))
), 10) - tail(x, 10))) / tail(x, 10) * 100) / 10
x3[12] = checkresiduals(MyArima, plot = F)$p.value

x4[12] = jarque.bera.test(na.omit(MyArima$residuals))$p.value

df = matrix(ncol = 7, nrow = 12)
df = data.frame(
  c(
    rep("Összes születés", 4),
    rep("Ezer főre eső születés", 4),
    rep("TTA", 4)
  ),
  rep(c(
    "diff(x)", "diff(x)", "log(diff(x))", "log(diff(x))"
  ), 3),
  
  x1,
  rep(c("ML", "CSS"), 6),
  percent(x2 / 100, d = 2),
  percent(x3, d = 2),
  percent(x4, d = 2)
)
names(df) = c(
  "Születési mutató",
  "Transzformáció",
  "Illesztett modell",
  "Becslés módszere",
  "MAPE",
  "Ljung-Box (p-érték)",
  "Jarque-Bera (p-érték)"
)
rownames(df) = NULL

```

